<?php
/**
 * SNN Learn — Course Builder
 *
 * One admin screen for building courses: a course list, then a chapter →
 * lesson tree with drag and drop, inline create / rename, status toggles and a
 * side panel that edits a post's details and course fields in place.
 *
 * The screen is a small vanilla JS app (assets/js/snn-course-builder.js)
 * talking to the REST routes below, all under snn-learn/v1/builder/.
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// ============================================================
// 1. HELPERS
// ============================================================

/** Statuses the builder shows and edits. Trash and auto-drafts stay out. */
function snn_builder_statuses() {
    return [ 'publish', 'draft', 'pending', 'private', 'future' ];
}

/** The statuses an author may set from the builder. */
function snn_builder_settable_statuses() {
    return [ 'publish', 'draft', 'pending', 'private' ];
}

function snn_builder_can_manage() {
    $pt = get_post_type_object( snn_learn_course_pt() );
    return $pt ? current_user_can( $pt->cap->edit_others_posts ) : current_user_can( 'edit_others_posts' );
}

function snn_builder_error( $code, $message, $status = 400 ) {
    return new WP_Error( $code, $message, [ 'status' => $status ] );
}

/** A course post by id, or a WP_Error. $role limits which role is accepted. */
function snn_builder_get( $id, $role = '' ) {
    $post = get_post( (int) $id );
    if ( ! $post || $post->post_type !== snn_learn_course_pt() || ! in_array( $post->post_status, snn_builder_statuses(), true ) ) {
        return snn_builder_error( 'snn_builder_not_found', 'That item does not exist or is in the trash.', 404 );
    }
    if ( $role && snn_learn_post_role( $post ) !== $role ) {
        return snn_builder_error( 'snn_builder_wrong_role', sprintf( 'That item is not a %s.', $role ) );
    }
    if ( ! current_user_can( 'edit_post', $post->ID ) ) {
        return snn_builder_error( 'snn_builder_forbidden', 'You cannot edit that item.', 403 );
    }
    return $post;
}

/** Direct children of a post, in builder order. */
function snn_builder_children( $parent_ids ) {
    $parent_ids = array_filter( array_map( 'intval', (array) $parent_ids ) );
    if ( ! $parent_ids ) {
        return [];
    }

    return get_posts( [
        'post_type'              => snn_learn_course_pt(),
        'post_parent__in'        => $parent_ids,
        'post_status'            => snn_builder_statuses(),
        'posts_per_page'         => -1,
        'orderby'                => [ 'menu_order' => 'ASC', 'ID' => 'ASC' ],
        'suppress_filters'       => true,
        'update_post_term_cache' => false,
    ] );
}

function snn_builder_next_order( $parent_id ) {
    global $wpdb;
    $max = $wpdb->get_var( $wpdb->prepare(
        "SELECT MAX(menu_order) FROM {$wpdb->posts} WHERE post_parent = %d AND post_type = %s AND post_status NOT IN ('trash','auto-draft','inherit')",
        (int) $parent_id, snn_learn_course_pt()
    ) );
    return null === $max ? 0 : (int) $max + 1;
}

/** Fields that can be generated by AI for a lesson, for the "AI 2/3" badge. */
function snn_builder_lesson_ai_fields() {
    static $fields = null;
    if ( null === $fields ) {
        $fields = array_values( array_filter( snn_cf_get_fields(), function ( $field ) {
            return $field['ai_enabled']
                && in_array( snn_learn_course_pt(), (array) $field['post_types'], true )
                && ( ! $field['roles'] || in_array( 'lesson', $field['roles'], true ) );
        } ) );
    }
    return $fields;
}

// ============================================================
// 2. NODE SHAPES
// ============================================================

function snn_builder_base_node( WP_Post $post ) {
    return [
        'id'        => (int) $post->ID,
        'title'     => $post->post_title,
        'slug'      => $post->post_name,
        'status'    => $post->post_status,
        'excerpt'   => $post->post_excerpt,
        'order'     => (int) $post->menu_order,
        'permalink' => get_permalink( $post ),
        'edit_url'  => get_edit_post_link( $post->ID, 'raw' ),
        'modified'  => mysql2date( get_option( 'date_format' ), $post->post_modified ),
    ];
}

function snn_builder_lesson_node( WP_Post $post ) {
    $keys      = snn_learn_lesson_keys();
    $subtitles = get_post_meta( $post->ID, $keys['subtitles'], true );
    $ai        = snn_builder_lesson_ai_fields();
    $ai_done   = 0;

    foreach ( $ai as $field ) {
        $value = get_post_meta( $post->ID, $field['slug'], true );
        if ( '' !== $value && [] !== $value && null !== $value ) {
            $ai_done++;
        }
    }

    return snn_builder_base_node( $post ) + [
        'role'         => 'lesson',
        'has_video'    => '' !== (string) get_post_meta( $post->ID, $keys['video'], true ),
        'subtitles'    => is_array( $subtitles ) ? count( $subtitles ) : ( '' !== (string) $subtitles ? 1 : 0 ),
        'duration'     => snn_learn_lesson_duration( $post->ID ),
        'free_preview' => (bool) get_post_meta( $post->ID, $keys['free_preview'], true ),
        'ai_done'      => $ai_done,
        'ai_total'     => count( $ai ),
    ];
}

function snn_builder_course_summary( WP_Post $course ) {
    $structure = snn_learn_course_structure( $course->ID );

    return snn_builder_base_node( $course ) + [
        'role'          => 'course',
        'thumb'         => get_the_post_thumbnail_url( $course, 'medium' ) ?: '',
        'chapter_count' => $structure['chapter_count'],
        'lesson_count'  => $structure['lesson_count'],
        'duration'      => $structure['duration'],
    ];
}

/** The full tree of one course, every builder status included. */
function snn_builder_course_tree( WP_Post $course ) {
    $chapters = snn_builder_children( $course->ID );
    $lessons  = snn_builder_children( wp_list_pluck( $chapters, 'ID' ) );

    $by_chapter = [];
    foreach ( $lessons as $lesson ) {
        $by_chapter[ $lesson->post_parent ][] = $lesson;
    }

    // Anything hanging below a lesson is outside the structure and invisible
    // to learners — count it so the builder can say so.
    $too_deep = count( snn_builder_children( wp_list_pluck( $lessons, 'ID' ) ) );

    $node = snn_builder_course_summary( $course ) + [
        'chapters' => [],
        'too_deep' => $too_deep,
    ];

    foreach ( $chapters as $chapter ) {
        $node['chapters'][] = snn_builder_base_node( $chapter ) + [
            'role'    => 'chapter',
            'lessons' => array_map( 'snn_builder_lesson_node', $by_chapter[ $chapter->ID ] ?? [] ),
        ];
    }

    return $node;
}

/** A node in whatever shape its role uses. */
function snn_builder_node( WP_Post $post ) {
    switch ( snn_learn_post_role( $post ) ) {
        case 'lesson':
            return snn_builder_lesson_node( $post );
        case 'chapter':
            return snn_builder_base_node( $post ) + [
                'role'    => 'chapter',
                'lessons' => array_map( 'snn_builder_lesson_node', snn_builder_children( $post->ID ) ),
            ];
        default:
            return snn_builder_course_summary( $post );
    }
}

// ============================================================
// 3. REST ROUTES
// ============================================================

add_action( 'rest_api_init', function () {
    $ns   = 'snn-learn/v1';
    $auth = [ 'permission_callback' => 'snn_builder_can_manage' ];

    register_rest_route( $ns, '/builder/courses', $auth + [
        'methods'  => 'GET',
        'callback' => 'snn_builder_rest_courses',
    ] );
    register_rest_route( $ns, '/builder/course/(?P<id>\d+)', $auth + [
        'methods'  => 'GET',
        'callback' => 'snn_builder_rest_course',
    ] );
    register_rest_route( $ns, '/builder/reorder', $auth + [
        'methods'  => 'POST',
        'callback' => 'snn_builder_rest_reorder',
    ] );
    register_rest_route( $ns, '/builder/create', $auth + [
        'methods'  => 'POST',
        'callback' => 'snn_builder_rest_create',
    ] );
    register_rest_route( $ns, '/builder/update', $auth + [
        'methods'  => 'POST',
        'callback' => 'snn_builder_rest_update',
    ] );
    register_rest_route( $ns, '/builder/duplicate', $auth + [
        'methods'  => 'POST',
        'callback' => 'snn_builder_rest_duplicate',
    ] );
    register_rest_route( $ns, '/builder/move', $auth + [
        'methods'  => 'POST',
        'callback' => 'snn_builder_rest_move',
    ] );
    register_rest_route( $ns, '/builder/trash', $auth + [
        'methods'  => 'POST',
        'callback' => 'snn_builder_rest_trash',
    ] );
    register_rest_route( $ns, '/builder/fields/(?P<id>\d+)', [
        [
            'methods'             => 'GET',
            'callback'            => 'snn_builder_rest_fields_get',
            'permission_callback' => 'snn_builder_can_manage',
        ],
        [
            'methods'             => 'POST',
            'callback'            => 'snn_builder_rest_fields_save',
            'permission_callback' => 'snn_builder_can_manage',
        ],
    ] );
} );

/** GET /builder/courses */
function snn_builder_rest_courses() {
    $courses = get_posts( [
        'post_type'        => snn_learn_course_pt(),
        'post_parent'      => 0,
        'post_status'      => snn_builder_statuses(),
        'posts_per_page'   => -1,
        'orderby'          => [ 'menu_order' => 'ASC', 'title' => 'ASC' ],
        'suppress_filters' => true,
    ] );

    // Counts include drafts, since that is what an author is building. One
    // query per level, however many courses there are.
    $chapters   = snn_builder_children( wp_list_pluck( $courses, 'ID' ) );
    $chapter_of = [];
    $counts     = [];
    foreach ( $chapters as $chapter ) {
        $chapter_of[ $chapter->ID ] = (int) $chapter->post_parent;
        $counts[ $chapter->post_parent ]['chapters'] = ( $counts[ $chapter->post_parent ]['chapters'] ?? 0 ) + 1;
    }
    if ( $chapter_of ) {
        global $wpdb;
        $ids  = implode( ',', array_keys( $chapter_of ) );
        $rows = $wpdb->get_results( $wpdb->prepare(
            "SELECT post_parent, COUNT(*) AS n FROM {$wpdb->posts} WHERE post_parent IN ($ids) AND post_type = %s AND post_status NOT IN ('trash','auto-draft','inherit') GROUP BY post_parent", // phpcs:ignore WordPress.DB.PreparedSQL -- ids are ints from WP_Post objects.
            snn_learn_course_pt()
        ) );
        foreach ( $rows as $row ) {
            $course = $chapter_of[ (int) $row->post_parent ];
            $counts[ $course ]['lessons'] = ( $counts[ $course ]['lessons'] ?? 0 ) + (int) $row->n;
        }
    }

    return rest_ensure_response( [
        'courses' => array_map( function ( $course ) use ( $counts ) {
            $node = snn_builder_course_summary( $course );
            $node['all_chapters'] = $counts[ $course->ID ]['chapters'] ?? 0;
            $node['all_lessons']  = $counts[ $course->ID ]['lessons'] ?? 0;
            return $node;
        }, $courses ),
    ] );
}

/** GET /builder/course/{id} */
function snn_builder_rest_course( WP_REST_Request $request ) {
    $course = snn_builder_get( $request['id'], 'course' );
    if ( is_wp_error( $course ) ) {
        return $course;
    }
    return rest_ensure_response( snn_builder_course_tree( $course ) );
}

/**
 * POST /builder/reorder
 * { course_id, chapters: [ { id, lessons: [ id, ... ] }, ... ] }
 *
 * Applies a whole course's order in one call. Only items already in this
 * course may appear, chapters must stay chapters and lessons lessons, and
 * only rows whose parent or position actually changed are written.
 */
function snn_builder_rest_reorder( WP_REST_Request $request ) {
    $course = snn_builder_get( $request['course_id'], 'course' );
    if ( is_wp_error( $course ) ) {
        return $course;
    }

    $chapters = snn_builder_children( $course->ID );
    $lessons  = snn_builder_children( wp_list_pluck( $chapters, 'ID' ) );

    $current = [];
    foreach ( array_merge( $chapters, $lessons ) as $post ) {
        $current[ $post->ID ] = $post;
    }
    $chapter_ids = array_map( 'intval', wp_list_pluck( $chapters, 'ID' ) );

    $plan = [];
    $seen = [];

    foreach ( array_values( (array) $request['chapters'] ) as $c_index => $entry ) {
        $chapter_id = (int) ( $entry['id'] ?? 0 );
        if ( ! in_array( $chapter_id, $chapter_ids, true ) || isset( $seen[ $chapter_id ] ) ) {
            return snn_builder_error( 'snn_builder_bad_order', 'The order sent does not match this course. Reload and try again.', 409 );
        }
        $seen[ $chapter_id ] = true;
        $plan[ $chapter_id ] = [ $course->ID, $c_index ];

        foreach ( array_values( (array) ( $entry['lessons'] ?? [] ) ) as $l_index => $lesson_id ) {
            $lesson_id = (int) $lesson_id;
            if ( ! isset( $current[ $lesson_id ] ) || in_array( $lesson_id, $chapter_ids, true ) || isset( $seen[ $lesson_id ] ) ) {
                return snn_builder_error( 'snn_builder_bad_order', 'The order sent does not match this course. Reload and try again.', 409 );
            }
            $seen[ $lesson_id ] = true;
            $plan[ $lesson_id ] = [ $chapter_id, $l_index ];
        }
    }

    global $wpdb;
    foreach ( $plan as $id => list( $parent, $order ) ) {
        $post = $current[ $id ];
        if ( (int) $post->post_parent !== $parent ) {
            // A new parent can collide with a sibling's slug, which only the
            // full update path resolves.
            wp_update_post( [ 'ID' => $id, 'post_parent' => $parent, 'menu_order' => $order ] );
        } elseif ( (int) $post->menu_order !== $order ) {
            $wpdb->update( $wpdb->posts, [ 'menu_order' => $order ], [ 'ID' => $id ] );
            clean_post_cache( $id );
        }
    }

    snn_learn_invalidate_structure( $course->ID );

    return rest_ensure_response( snn_builder_course_tree( get_post( $course->ID ) ) );
}

/**
 * POST /builder/create
 * { parent_id, titles: [ ... ], status }  — one or many items under a parent
 * { parent_id: course, outline: "text" }  — chapters and lessons from an outline
 *
 * parent 0 makes courses, a course makes chapters, a chapter makes lessons.
 */
function snn_builder_rest_create( WP_REST_Request $request ) {
    $parent_id = (int) $request['parent_id'];
    $status    = in_array( $request['status'], snn_builder_settable_statuses(), true ) ? $request['status'] : 'draft';

    if ( 'publish' === $status && ! current_user_can( get_post_type_object( snn_learn_course_pt() )->cap->publish_posts ) ) {
        $status = 'draft';
    }

    $parent = null;
    if ( $parent_id ) {
        $parent = snn_builder_get( $parent_id );
        if ( is_wp_error( $parent ) ) {
            return $parent;
        }
        if ( 'lesson' === snn_learn_post_role( $parent ) ) {
            return snn_builder_error( 'snn_builder_too_deep', 'Lessons cannot have children.' );
        }
    }

    if ( null !== $request['outline'] ) {
        if ( ! $parent || 'course' !== snn_learn_post_role( $parent ) ) {
            return snn_builder_error( 'snn_builder_outline_parent', 'An outline can only be added to a course.' );
        }
        $created = snn_builder_create_outline( $parent, (string) $request['outline'], $status );
    } else {
        $created = [];
        $order   = snn_builder_next_order( $parent_id );

        foreach ( (array) $request['titles'] as $title ) {
            $title = trim( sanitize_text_field( (string) $title ) );
            if ( '' === $title ) {
                continue;
            }
            $id = snn_builder_insert( $title, $parent_id, $order++, $status );
            if ( is_wp_error( $id ) ) {
                return $id;
            }
            $created[] = $id;
        }
    }

    if ( is_wp_error( $created ) ) {
        return $created;
    }
    if ( ! $created ) {
        return snn_builder_error( 'snn_builder_nothing', 'Nothing to create — every title was empty.' );
    }

    return rest_ensure_response( [
        'created' => array_map( function ( $id ) {
            return snn_builder_node( get_post( $id ) );
        }, $created ),
    ] );
}

function snn_builder_insert( $title, $parent_id, $order, $status ) {
    return wp_insert_post( wp_slash( [
        'post_type'   => snn_learn_course_pt(),
        'post_title'  => $title,
        'post_parent' => (int) $parent_id,
        'menu_order'  => (int) $order,
        'post_status' => $status,
        'post_author' => get_current_user_id(),
    ] ), true );
}

/**
 * Creates chapters and lessons from a plain-text outline.
 *
 * A line with no indent is a chapter. An indented line, or one starting with
 * "-", "*" or "•", is a lesson in the chapter above it. Returns the ids of the
 * new chapters (their lessons come back inside the chapter nodes).
 */
function snn_builder_create_outline( WP_Post $course, $outline, $status ) {
    $chapter_ids   = [];
    $chapter_id    = 0;
    $chapter_order = snn_builder_next_order( $course->ID );
    $lesson_order  = 0;

    foreach ( preg_split( '/\r\n|\r|\n/', $outline ) as $line ) {
        if ( '' === trim( $line ) ) {
            continue;
        }

        $is_lesson = (bool) preg_match( '/^(\s+|\s*[-*•]\s*)/u', $line );
        $title     = trim( sanitize_text_field( preg_replace( '/^\s*[-*•]?\s*/u', '', $line ) ) );
        if ( '' === $title ) {
            continue;
        }

        if ( ! $is_lesson || ! $chapter_id ) {
            // A lesson before any chapter gets a chapter to live in.
            $chapter_title = $is_lesson ? 'Chapter ' . ( count( $chapter_ids ) + 1 ) : $title;
            $chapter_id    = snn_builder_insert( $chapter_title, $course->ID, $chapter_order++, $status );
            if ( is_wp_error( $chapter_id ) ) {
                return $chapter_id;
            }
            $chapter_ids[] = $chapter_id;
            $lesson_order  = 0;

            if ( ! $is_lesson ) {
                continue;
            }
        }

        $lesson_id = snn_builder_insert( $title, $chapter_id, $lesson_order++, $status );
        if ( is_wp_error( $lesson_id ) ) {
            return $lesson_id;
        }
    }

    return $chapter_ids;
}

/**
 * POST /builder/update
 * { id, title?, slug?, excerpt?, status?, cascade? }
 *
 * cascade applies the status to every chapter and lesson below the item too.
 */
function snn_builder_rest_update( WP_REST_Request $request ) {
    $post = snn_builder_get( $request['id'] );
    if ( is_wp_error( $post ) ) {
        return $post;
    }

    $data = [ 'ID' => $post->ID ];

    if ( null !== $request['title'] ) {
        $title = trim( sanitize_text_field( (string) $request['title'] ) );
        if ( '' === $title ) {
            return snn_builder_error( 'snn_builder_empty_title', 'The title cannot be empty.' );
        }
        $data['post_title'] = $title;
    }
    if ( null !== $request['slug'] ) {
        $data['post_name'] = sanitize_title( (string) $request['slug'] );
    }
    if ( null !== $request['excerpt'] ) {
        $data['post_excerpt'] = sanitize_textarea_field( (string) $request['excerpt'] );
    }

    $status = null;
    if ( null !== $request['status'] ) {
        $status = (string) $request['status'];
        if ( ! in_array( $status, snn_builder_settable_statuses(), true ) ) {
            return snn_builder_error( 'snn_builder_bad_status', 'Unknown status.' );
        }
        if ( 'publish' === $status && ! current_user_can( 'publish_post', $post->ID ) ) {
            return snn_builder_error( 'snn_builder_forbidden', 'You cannot publish that item.', 403 );
        }
        $data['post_status'] = $status;
    }

    if ( count( $data ) > 1 ) {
        $result = wp_update_post( wp_slash( $data ), true );
        if ( is_wp_error( $result ) ) {
            return $result;
        }
    }

    if ( $status && $request['cascade'] ) {
        $children    = snn_builder_children( $post->ID );
        $descendants = array_merge( $children, snn_builder_children( wp_list_pluck( $children, 'ID' ) ) );
        foreach ( $descendants as $child ) {
            if ( $child->post_status !== $status && current_user_can( 'edit_post', $child->ID ) ) {
                wp_update_post( [ 'ID' => $child->ID, 'post_status' => $status ] );
            }
        }
    }

    return rest_ensure_response( snn_builder_node( get_post( $post->ID ) ) );
}

/**
 * POST /builder/duplicate { id }
 *
 * Copies the item with its meta, terms and whole subtree, as the last sibling.
 * The copy itself starts as a draft; items below it keep their status, which
 * a draft parent hides from learners anyway.
 */
function snn_builder_rest_duplicate( WP_REST_Request $request ) {
    $post = snn_builder_get( $request['id'] );
    if ( is_wp_error( $post ) ) {
        return $post;
    }

    $copy = snn_builder_copy_post( $post, (int) $post->post_parent, snn_builder_next_order( $post->post_parent ), true );
    if ( is_wp_error( $copy ) ) {
        return $copy;
    }

    return rest_ensure_response( snn_builder_node( get_post( $copy ) ) );
}

function snn_builder_copy_post( WP_Post $post, $parent_id, $order, $is_root ) {
    $new_id = wp_insert_post( wp_slash( [
        'post_type'    => $post->post_type,
        'post_title'   => $is_root ? $post->post_title . ' (Copy)' : $post->post_title,
        'post_content' => $post->post_content,
        'post_excerpt' => $post->post_excerpt,
        'post_status'  => $is_root ? 'draft' : $post->post_status,
        'post_parent'  => (int) $parent_id,
        'menu_order'   => (int) $order,
        'post_author'  => get_current_user_id(),
        'comment_status' => $post->comment_status,
        'ping_status'  => $post->ping_status,
    ] ), true );

    if ( is_wp_error( $new_id ) ) {
        return $new_id;
    }

    $skip = [ '_edit_lock', '_edit_last', '_wp_old_slug', '_wp_old_date', SNN_LEARN_STRUCTURE_META ];
    foreach ( get_post_meta( $post->ID ) as $key => $values ) {
        if ( in_array( $key, $skip, true ) ) {
            continue;
        }
        foreach ( $values as $value ) {
            add_post_meta( $new_id, $key, wp_slash( maybe_unserialize( $value ) ) );
        }
    }

    foreach ( get_object_taxonomies( $post->post_type ) as $taxonomy ) {
        $terms = wp_get_object_terms( $post->ID, $taxonomy, [ 'fields' => 'ids' ] );
        if ( ! is_wp_error( $terms ) && $terms ) {
            wp_set_object_terms( $new_id, $terms, $taxonomy );
        }
    }

    foreach ( snn_builder_children( $post->ID ) as $child ) {
        $result = snn_builder_copy_post( $child, $new_id, $child->menu_order, false );
        if ( is_wp_error( $result ) ) {
            return $result;
        }
    }

    return $new_id;
}

/**
 * POST /builder/move { id, target_id }
 *
 * A lesson moves into a chapter (of any course), a chapter into a course.
 * The item lands at the end of its new parent.
 */
function snn_builder_rest_move( WP_REST_Request $request ) {
    $post = snn_builder_get( $request['id'] );
    if ( is_wp_error( $post ) ) {
        return $post;
    }

    $role        = snn_learn_post_role( $post );
    $target_role = [ 'lesson' => 'chapter', 'chapter' => 'course' ][ $role ] ?? '';
    if ( ! $target_role ) {
        return snn_builder_error( 'snn_builder_cannot_move', 'Only chapters and lessons can be moved.' );
    }

    $target = snn_builder_get( $request['target_id'], $target_role );
    if ( is_wp_error( $target ) ) {
        return $target;
    }
    if ( (int) $post->post_parent === (int) $target->ID ) {
        return snn_builder_error( 'snn_builder_same_parent', 'It is already there.' );
    }

    $result = wp_update_post( [
        'ID'          => $post->ID,
        'post_parent' => $target->ID,
        'menu_order'  => snn_builder_next_order( $target->ID ),
    ], true );

    if ( is_wp_error( $result ) ) {
        return $result;
    }

    return rest_ensure_response( [ 'moved' => true, 'course_id' => snn_learn_get_course_id( $target->ID ) ] );
}

/** POST /builder/trash { id } — trashes the item and everything below it. */
function snn_builder_rest_trash( WP_REST_Request $request ) {
    $post = snn_builder_get( $request['id'] );
    if ( is_wp_error( $post ) ) {
        return $post;
    }
    if ( ! current_user_can( 'delete_post', $post->ID ) ) {
        return snn_builder_error( 'snn_builder_forbidden', 'You cannot trash that item.', 403 );
    }

    $children    = snn_builder_children( $post->ID );
    $descendants = array_merge( snn_builder_children( wp_list_pluck( $children, 'ID' ) ), $children );

    foreach ( $descendants as $child ) {
        wp_trash_post( $child->ID );
    }
    wp_trash_post( $post->ID );

    return rest_ensure_response( [ 'trashed' => 1 + count( $descendants ) ] );
}

/** GET /builder/fields/{id} — the course field editors for one post, as HTML. */
function snn_builder_rest_fields_get( WP_REST_Request $request ) {
    $post = snn_builder_get( $request['id'] );
    if ( is_wp_error( $post ) ) {
        return $post;
    }

    if ( ! snn_cf_enabled() ) {
        return rest_ensure_response( [ 'enabled' => false, 'html' => '' ] );
    }

    ob_start();
    foreach ( snn_cf_groups_for( $post->post_type, $post ) as $group => $fields ) {
        echo '<section class="snn-cf-metabox snb-field-group">';
        printf(
            '<div class="snb-field-group-head"><h3>%s</h3><span class="snn-cf-toolbar">'
            . '<button type="button" class="button-link snn-cf-toggle-all" data-open="1">Expand all</button>'
            . '<button type="button" class="button-link snn-cf-toggle-all" data-open="0">Collapse all</button>'
            . '</span></div>',
            esc_html( $group )
        );
        echo '<div class="snn-cf-grid">';
        foreach ( $fields as $field ) {
            snn_cf_render_field( $field, get_post_meta( $post->ID, $field['slug'], true ) );
        }
        echo '</div></section>';
    }

    return rest_ensure_response( [ 'enabled' => true, 'html' => ob_get_clean() ] );
}

/** POST /builder/fields/{id} — saves the side panel's field form. */
function snn_builder_rest_fields_save( WP_REST_Request $request ) {
    $post = snn_builder_get( $request['id'] );
    if ( is_wp_error( $post ) ) {
        return $post;
    }
    if ( ! snn_cf_enabled() ) {
        return snn_builder_error( 'snn_builder_fields_off', 'Course fields are turned off.' );
    }

    // Body params arrive unslashed from the REST server.
    $params = $request->get_body_params();

    snn_cf_write_values(
        $post->ID,
        snn_cf_fields_for( $post->post_type, $post ),
        (array) ( $params['snn_cf_present'] ?? [] ),
        is_array( $params['snn_cf'] ?? null ) ? $params['snn_cf'] : []
    );

    // Field saves bypass save_post, so bump the modified date by hand; the
    // course's "last updated" should reflect lesson edits.
    wp_update_post( [ 'ID' => $post->ID ] );

    return rest_ensure_response( snn_builder_node( get_post( $post->ID ) ) );
}

// ============================================================
// 4. ADMIN PAGE
// ============================================================

add_action( 'admin_enqueue_scripts', function ( $hook ) {
    if ( false === strpos( (string) $hook, 'snn-learn-builder' ) ) {
        return;
    }

    $base = plugin_dir_url( __FILE__ );
    $dir  = plugin_dir_path( __FILE__ );
    $ver  = '1.0.' . ( @filemtime( $dir . 'assets/js/snn-course-builder.js' ) ?: 0 ); // phpcs:ignore WordPress.PHP.NoSilencedErrors

    wp_enqueue_style( 'snn-course-builder', $base . 'assets/css/snn-course-builder.css', [], $ver );
    wp_enqueue_script( 'snn-course-builder', $base . 'assets/js/snn-course-builder.js', [], $ver, true );

    $pt = get_post_type_object( snn_learn_course_pt() );

    // phpcs:disable WordPress.Security.NonceVerification -- read-only view state.
    wp_add_inline_script( 'snn-course-builder', 'window.SNN_BUILDER = ' . wp_json_encode( [
        'restUrl'        => esc_url_raw( rest_url( 'snn-learn/v1/builder/' ) ),
        'nonce'          => wp_create_nonce( 'wp_rest' ),
        'pageUrl'        => admin_url( 'admin.php?page=snn-learn-builder' ),
        'postType'       => snn_learn_course_pt(),
        'postTypeReady'  => (bool) $pt,
        'listUrl'        => admin_url( 'edit.php?post_type=' . snn_learn_course_pt() ),
        'fieldsUrl'      => admin_url( 'admin.php?page=snn-learn-course-fields' ),
        'fieldsEnabled'  => snn_cf_enabled(),
        'canPublish'     => $pt ? current_user_can( $pt->cap->publish_posts ) : false,
        'initialCourse'  => isset( $_GET['course'] ) ? absint( $_GET['course'] ) : 0,
        'initialFocus'   => isset( $_GET['focus'] ) ? absint( $_GET['focus'] ) : 0,
    ] ) . ';', 'before' );
    // phpcs:enable
} );

function snn_learn_builder_page() {
    if ( ! snn_builder_can_manage() ) {
        wp_die( 'You do not have permission to build courses.' );
    }
    ?>
    <div class="wrap snb-wrap">
        <h1 class="screen-reader-text">Course Builder</h1>
        <div id="snb-app" class="snb-app" aria-live="polite">
            <p class="snb-loading">Loading courses…</p>
        </div>
        <noscript><p>The Course Builder needs JavaScript.</p></noscript>
    </div>
    <?php
}
